model_params:
  model: MultiHeadNet
  arch: resnet18
  pretrained: True
  num_classes:
    - 168
    - 11
    - 7

args:
  logdir: "./logs/bengali_logs"
  seed: 65
  check: False
  verbose: True

runner_params:  # OPTIONAL KEYWORD, параметры для инициализации Runner
  # Например для SupervisedRunner
  input_key: "images"  # Пример
  output_key:
    - "logit_grapheme_root"
    - "logit_vowel_diacritic"
    - "logit_consonant_diacritic"
  input_target_key:
    - "grapheme_roots"
    - "vowel_diacritics"
    - "consonant_diacritics"

stages:
  data_params:
    batch_size: 128
    num_workers: 2

    train_csv: "train.csv"
    data_folder: "../input/grapheme-imgs-128x128/"

  state_params:
    main_metric: loss
    minimize_metric: True

  criterion_params:
    _key_value: True
    ce:
      criterion: CrossEntropyLoss

  optimizer_params:  # REQUIRED KEYWORD, параметры для оптимизатора
    optimizer: Adam  # REQUIRED KEYWORD, имя оптимизатора
    lr: 0.003
    weight_decay: 0.0001

  scheduler_params:  # REQUIRED KEYWORD, параметры для lr-scheduler
    scheduler: StepLR  # REQUIRED KEYWORD, имя lr-scheduler
    # на этом уровне могут лежать параметры для __init__ данного lr-scheduler, например
    step_size: 10
    gamma: 0.3

  stage1:  # Все, что не ключевое слово, расценивается, как имя стейджа. Для тренировки в Catalyst требуется хотябы один стейдж. Имя может быть произвольным
    state_params:  # Вы можете переопределить любые параметры, для конкретного стейджа, например
      num_epochs: 2

    callbacks_params:  # REQUIRED KEYWORD, самая важная часть, тут записываются все коллбеки для данного стейджа
      # коллбеки записываются через key-value
      loss_grapheme_roots:
        callback: CriterionCallback  # KEYWORD имя коллбека
        input_key: "grapheme_roots"
        output_key: "logit_grapheme_root"
        criterion_key: "ce"
        prefix: "loss_gr"

      loss_vowel_diacritics:
        callback: CriterionCallback  # KEYWORD имя коллбека
        input_key: "vowel_diacritics"
        output_key: "logit_vowel_diacritic"
        criterion_key: "ce"
        prefix: "loss_vd"

      loss_consonant_diacritics:
        callback: CriterionCallback  # KEYWORD имя коллбека
        input_key: "consonant_diacritics"
        output_key: "logit_consonant_diacritic"
        criterion_key: "ce"
        prefix: "loss_cd"

      loss_aggregator:
        callback: CriterionAggregatorCallback
        prefix: "loss"
        loss_aggregate_fn: "sum"
        loss_keys:
          - "loss_gr"
          - "loss_vd"
          - "loss_cd"

      optimizer:
        callback: OptimizerCallback
      scheduler:
        callback: SchedulerCallback
        reduce_metric: loss
      saver:
        callback: CheckpointCallback
        save_n_best: 2
      metrics:
        callback: HMacroAveragedRecall

