model_params:
  model: MultiHeadNet
  encoder: "resnet34"
  pretrained: True
  num_classes: [168, 11, 7]

args:
  logdir: "./logs/bengali_logs"
  seed: 65
  check: False
  verbose: True

runner_params:  # OPTIONAL KEYWORD, параметры для инициализации Runner
  # Например для SupervisedRunner
  input_key: "image"  # Пример
  output_key:
    - "logit_grapheme_root"
    - "logit_vowel_diacritic"
    - "logit_consonant_diacritic"
  input_target_key:
    - "grapheme_root"
    - "vowel_diacritic"
    - "consonant_diacritic"

stages:
  data_params:
    batch_size: 512

    train_csv: "train.csv"
    data_folder: "../input/grapheme-imgs-128x128/"
    test_run: True

  state_params:
    main_metric: loss
    minimize_metric: True

  criterion_params:
    _key_value: True
    ce:
      criterion: CrossEntropyLoss

  callbacks_params:

    loss_mixup:
      callback: CustomMixupCallback
      fields: ["image"]
      input_key: ["grapheme_root", "vowel_diacritic", "consonant_diacritic"]
      output_key: ["logit_grapheme_root", "logit_vowel_diacritic", "logit_consonant_diacritic"]
      criterion_key: "ce"
      prefix: "loss"
      weight_grapheme_root: 2.0
      weight_vowel_diacritic: 1.0
      weight_consonant_diacritic: 1.0

    saver:
      callback: CheckpointCallback
      save_n_best: 3

    metrics:
      callback: HMacroAveragedRecall

    optimizer:
      callback: OptimizerCallback

    scheduler:
      callback: SchedulerCallback
      reduce_metric: loss

  stage1:
    state_params:
      num_epochs: 80

    callbacks_params:
      unfreeze:
        callback: UnFreezeCallback

    optimizer_params:  # Пример, переопределенного оптимизатора
      optimizer: AdamW
      lr: 5e-3

    scheduler_params:
      scheduler: OneCycleLRWithWarmup
      init_lr: 0.001
      num_steps: 50
      warmup_steps: 15
      lr_range: [0.008, 0.00008]
      momentum_range: [0.85, 0.95]

