model_params:
  model: Efficient
  encoder: "efficientnet-b0"
  num_classes: [168, 11, 7]
  dropout: 0.0

args:
  logdir: "./logs/bengali_logs"
  seed: 65
  check: False
  verbose: True

runner_params:  # OPTIONAL KEYWORD, параметры для инициализации Runner
  # Например для SupervisedRunner
  input_key: "image"  # Пример
  output_key:
    - "logit_grapheme_root"
    - "logit_vowel_diacritic"
    - "logit_consonant_diacritic"
  input_target_key:
    - "grapheme_root"
    - "vowel_diacritic"
    - "consonant_diacritic"

stages:
  data_params:
    batch_size: 256
    num_workers: 2
    train_csv: "train.csv"
    data_folder: "../input/grapheme-imgs-128x128/"
    train_aug_name: "mixup_aug"

  state_params:
    main_metric: hmar
    minimize_metric: False

  criterion_params:
    _key_value: True
    ce:
      criterion: CrossEntropyLoss

  callbacks_params:

    loss_mixup:
      callback: CustomMixupCallback
      fields: ["image"]
      input_key: ["grapheme_root", "vowel_diacritic", "consonant_diacritic"]
      output_key: ["logit_grapheme_root", "logit_vowel_diacritic", "logit_consonant_diacritic"]
      criterion_key: "ce"
      prefix: "loss"
      weight_grapheme_root: 2.0
      weight_vowel_diacritic: 1.0
      weight_consonant_diacritic: 1.0

    saver:
      callback: CheckpointCallback
      save_n_best: 3

    metrics:
      callback: HMacroAveragedRecall

    optimizer:
      callback: OptimizerCallback

    scheduler:
      callback: SchedulerCallback
      reduce_metric: loss

  stage1:
    state_params:
      num_epochs: 50

    callbacks_params:
      checkpoint_loader:
        callback: CheckpointLoader
        checkpoint_path: "../input/bengaliutils/efnet_mixup_80ep.pth"

    optimizer_params:  # Пример, переопределенного оптимизатора
      optimizer: AdamW
      lr: 0.0005

    scheduler_params:
      scheduler: ReduceLROnPlateau
      factor: 0.5
      patience: 5
      verbose: True
      min_lr: 0.0000005
