model_params:
  model: Efficient
  encoder: "efficientnet-b0"
  num_classes: [168, 11, 7]
  dropout: 0.0
  pooling: "Gem"
  activation: "Mish"

args:
  logdir: "./logs/bengali_logs"
  seed: 65
  check: False
  verbose: True

runner_params:  # OPTIONAL KEYWORD, параметры для инициализации Runner
  # Например для SupervisedRunner
  input_key: "image"  # Пример
  output_key:
    - "logit_grapheme_root"
    - "logit_vowel_diacritic"
    - "logit_consonant_diacritic"
  input_target_key:
    - "grapheme_root"
    - "vowel_diacritic"
    - "consonant_diacritic"

#distributed_params:  # OPTIONAL KEYWORD, параметры для distributed training и NVIDIA Apex
#  opt_level: O1

stages:
  data_params:
    batch_size: 256
    num_workers: 4
    train_csv: "train.csv"
    data_folder: "../input/grapheme-imgs-128x128/"
    processed: False

  state_params:
    main_metric: hmar
    minimize_metric: False

  criterion_params:
    _key_value: True
    ce:
      criterion: CrossEntropyLoss

  callbacks_params:

    saver:
      callback: CheckpointCallback
      save_n_best: 3

    metrics:
      callback: HMacroAveragedRecall

    optimizer:
      callback: OptimizerCallback

    scheduler:
      callback: SchedulerCallback
      reduce_metric: loss

  stage1:

    data_params:
      train_aug_name: "simple_aug"

    state_params:
      num_epochs: 5

    optimizer_params:
      optimizer: AdamW

    scheduler_params:
      scheduler: OneCycleLRWithWarmup
      init_lr: 0.001
      num_steps: 5
      warmup_steps: 1
      lr_range: [0.005, 0.001]

    callbacks_params:
      loss_grapheme_roots:
        callback: CriterionCallback
        input_key: "grapheme_root"
        output_key: "logit_grapheme_root"
        criterion_key: "ce"
        prefix: "loss_gr"

      loss_vowel_diacritics:
        callback: CriterionCallback
        input_key: "vowel_diacritic"
        output_key: "logit_vowel_diacritic"
        criterion_key: "ce"
        prefix: "loss_vd"

      loss_consonant_diacritics:
        callback: CriterionCallback
        input_key: "consonant_diacritic"
        output_key: "logit_consonant_diacritic"
        criterion_key: "ce"
        prefix: "loss_cd"

      loss_aggregator:
        callback: CriterionAggregatorCallback
        prefix: "loss"
        loss_aggregate_fn: "weighted_sum"
        loss_keys:
          loss_gr: 2.0
          loss_vd: 1.0
          loss_cd: 1.0

  stage2:
    data_params:
      train_aug_name: "mixup_aug"

    state_params:
      num_epochs: 75

    optimizer_params:
      optimizer: AdamW

    scheduler_params:
      scheduler: OneCycleLRWithWarmup
      init_lr: 0.001
      num_steps: 75
      warmup_steps: 5
      lr_range: [0.005, 0.000005]

    callbacks_params:
      loss_mixup:
        callback: MixupCutmixCallback
        fields: ["image"]
        input_key: ["grapheme_root", "vowel_diacritic", "consonant_diacritic"]
        output_key: ["logit_grapheme_root", "logit_vowel_diacritic", "logit_consonant_diacritic"]
        criterion_key: "ce"
        prefix: "loss"
        weight_grapheme_root: 2.0
        weight_vowel_diacritic: 1.0
        weight_consonant_diacritic: 1.0

