model_params:
  model: EfficientNew
  encoder: efficientnet_b0
  num_classes:
    - 168
    - 11
    - 7

args:
  logdir: "./logs/bengali_logs"
  seed: 65
  check: False
  verbose: True

runner_params:
  input_key: "image"
  output_key:
    - "logit_grapheme_root"
    - "logit_vowel_diacritic"
    - "logit_consonant_diacritic"
  input_target_key:
    - "grapheme_root"
    - "vowel_diacritic"
    - "consonant_diacritic"

stages:
  data_params:
    batch_size: 16
    num_workers: 4
    train_csv_path: "../input/bengaliai-cv19/"
    train_csv_name: "train.csv"
    data_folder: "../input/grapheme-imgs-128x128/"
    train_aug_name: "mixup_aug"
    test_run: True

  state_params:
    main_metric: hmar
    minimize_metric: False

  criterion_params:
    _key_value: True
    ce:
      criterion: CrossEntropyLoss

  callbacks_params:

    loss_mixup:
      callback: MixupCutmixCallback
      fields: ["image"]
      input_key: ["grapheme_root", "vowel_diacritic", "consonant_diacritic"]
      output_key: ["logit_grapheme_root", "logit_vowel_diacritic", "logit_consonant_diacritic"]
      criterion_key: "ce"
      prefix: "loss"
      weight_grapheme_root: 7
      weight_vowel_diacritic: 1
      weight_consonant_diacritic: 2

    saver:
      callback: CheckpointCallback
      save_n_best: 3

    metrics:
      callback: HMacroAveragedRecall

    optimizer:
      callback: OptimizerCallback

    scheduler:
      callback: SchedulerCallback
      reduce_metric: hmar

  stage1:
    state_params:
      num_epochs: 100

    optimizer_params:
      optimizer: AdamW

    scheduler_params:
      scheduler: OneCycleLRWithWarmup
      init_lr: 0.0005
      num_steps: 95
      warmup_steps: 5
      lr_range: [0.002, 0.000005]
