model_params:
  model: EfficientNew
  encoder: "tf_efficientnet_b3_ns"
  num_classes: [168, 11, 7]

args:
  logdir: "./logs/bengali_logs"
  seed: 65
  check: False
  verbose: True

runner_params:
  input_key: "image"
  output_key:
    - "logit_grapheme_root"
    - "logit_vowel_diacritic"
    - "logit_consonant_diacritic"
  input_target_key:
    - "grapheme_root"
    - "vowel_diacritic"
    - "consonant_diacritic"

distributed_params:
  opt_level: O2

stages:
  data_params:
    batch_size: 160
    num_workers: 8
    train_csv_path: "../input/bengaliutils2/"
    train_csv_name: "train_with_fold.csv"
    data_folder: "../input/137x236-images/137x236_images/"
    train_aug_name: "mixup_aug"
    fold: 1
    processed: False

  state_params:
    main_metric: hmar
    minimize_metric: False

  criterion_params:
    _key_value: True
    ce:
      criterion: CrossEntropyLoss

  callbacks_params:

    loss_grapheme_roots:
      callback: CriterionCallback
      input_key: "grapheme_root"
      output_key: "logit_grapheme_root"
      criterion_key: "ce"
      prefix: "loss_gr"

    loss_vowel_diacritics:
      callback: CriterionCallback
      input_key: "vowel_diacritic"
      output_key: "logit_vowel_diacritic"
      criterion_key: "ce"
      prefix: "loss_vd"

    loss_consonant_diacritics:
      callback: CriterionCallback
      input_key: "consonant_diacritic"
      output_key: "logit_consonant_diacritic"
      criterion_key: "ce"
      prefix: "loss_cd"

    loss_aggregator:
      callback: CriterionAggregatorCallback
      prefix: "loss"
      loss_aggregate_fn: "weighted_sum"
      loss_keys:
        loss_gr: 2.0
        loss_vd: 1.0
        loss_cd: 1.0

    saver:
      callback: CheckpointCallback
      save_n_best: 3

    metrics:
      callback: HMacroAveragedRecall

    optimizer:
      callback: OptimizerCallback

    scheduler:
      callback: SchedulerCallback
      reduce_metric: loss

  stage1:
    state_params:
      num_epochs: 3

    optimizer_params:
      optimizer: AdamW

    scheduler_params:
      scheduler: OneCycleLRWithWarmup
      init_lr: 0.00002
      num_steps: 32
      warmup_steps: 0
      lr_range: [0.00002, 0.000001]

    callbacks_params:
      checkpoint_loader:
        callback: CheckpointLoader
        checkpoint_path: "../input/bengaliutils2/b3_9827_f1.pth"

