model_params:
  model: EfficientNew
  encoder: "efficientnet_b0"
  num_classes: [168, 11, 7]
  activation: "Mish"

args:
  logdir: "./logs/bengali_logs"
  seed: 65
  check: False
  verbose: True

runner_params:  # OPTIONAL KEYWORD, параметры для инициализации Runner
  # Например для SupervisedRunner
  input_key: "image"  # Пример
  output_key:
    - "logit_grapheme_root"
    - "logit_vowel_diacritic"
    - "logit_consonant_diacritic"
  input_target_key:
    - "grapheme_root"
    - "vowel_diacritic"
    - "consonant_diacritic"

#distributed_params:  # OPTIONAL KEYWORD, параметры для distributed training и NVIDIA Apex
#  opt_level: O1

stages:
  data_params:
    batch_size: 256
    num_workers: 4
    train_csv_path: "../input/bengaliutils2/"
    train_csv_name: "train_with_fold.csv"
    data_folder: "../input/grapheme-imgs-128x128/"
    train_aug_name: "gridmask_aug"
    fold: 0
    processed: False
   # samplers_params:  # KEYWORD, параметры sampler для каждого лоадера, такое же API, как в loaders_params
   #   train:
   #     sampler: BalanceSampler
   #     df_path: "../input/bengaliutils2/train_with_fold.csv"

  state_params:
    main_metric: hmar
    minimize_metric: False

  criterion_params:
    _key_value: True
    ce:
      criterion: CrossEntropyLoss

  callbacks_params:

    loss_grapheme_roots:
      callback: CriterionCallback
      input_key: "grapheme_root"
      output_key: "logit_grapheme_root"
      criterion_key: "ce"
      prefix: "loss_gr"

    loss_vowel_diacritics:
      callback: CriterionCallback
      input_key: "vowel_diacritic"
      output_key: "logit_vowel_diacritic"
      criterion_key: "ce"
      prefix: "loss_vd"

    loss_consonant_diacritics:
      callback: CriterionCallback
      input_key: "consonant_diacritic"
      output_key: "logit_consonant_diacritic"
      criterion_key: "ce"
      prefix: "loss_cd"

    loss_aggregator:
      callback: CriterionAggregatorCallback
      prefix: "loss"
      loss_aggregate_fn: "weighted_sum"
      loss_keys:
        loss_gr: 10.0
        loss_vd: 1.0
        loss_cd: 2.0

    saver:
      callback: CheckpointCallback
      save_n_best: 3

    metrics:
      callback: HMacroAveragedRecall

    optimizer:
      callback: OptimizerCallback

    scheduler:
      callback: SchedulerCallback
      reduce_metric: loss

  stage1:
    state_params:
      num_epochs: 65

    optimizer_params:
      optimizer: AdamW

    scheduler_params:
      scheduler: OneCycleLRWithWarmup
      init_lr: 0.001
      num_steps: 62
      warmup_steps: 5
      lr_range: [0.003, 0.000005]

