model_params:
  model: EfficientNew
  num_classes: [168, 11, 7]
  encoder: "efficientnet_b4"
  activation: "Mish"

args:
  logdir: "./logs"
  seed: 65
  check: False
  verbose: True

runner_params:  # OPTIONAL KEYWORD, параметры для инициализации Runner
  # Например для SupervisedRunner
  input_key: "image"  # Пример
  output_key:
    - "logit_grapheme_root"
    - "logit_vowel_diacritic"
    - "logit_consonant_diacritic"
  input_target_key:
    - "grapheme_root"
    - "vowel_diacritic"
    - "consonant_diacritic"

#distributed_params:  # OPTIONAL KEYWORD, параметры для distributed training и NVIDIA Apex
#  opt_level: O1

stages:
  data_params:
    batch_size: 256
    num_workers: 4
    train_csv_path: "../input/bengaliutils2/"
    train_csv_name: "train_with_fold.csv"
    data_folder: "../input/grapheme-imgs-128x128/"
    train_aug_name: "mixup_aug"
    fold: 1
    processed: False
   # samplers_params:  # KEYWORD, параметры sampler для каждого лоадера, такое же API, как в loaders_params
   #   train:
   #     sampler: BalanceSampler
   #     df_path: "../input/bengaliutils2/train_with_fold.csv"

  state_params:
    main_metric: hmar
    minimize_metric: False

  criterion_params:
    _key_value: True
    ce:
      criterion: CrossEntropyLoss

  callbacks_params:

    loss_mixup:
      callback: MixupCutmixCallback
      fields: ["image"]
      input_key: ["grapheme_root", "vowel_diacritic", "consonant_diacritic"]
      output_key: ["logit_grapheme_root", "logit_vowel_diacritic", "logit_consonant_diacritic"]
      criterion_key: "ce"
      prefix: "loss"
      weight_grapheme_root: 7
      weight_vowel_diacritic: 1
      weight_consonant_diacritic: 2

    saver:
      callback: CheckpointCallback
      save_n_best: 3

    metrics:
      callback: HMacroAveragedRecall

    optimizer:
      callback: OptimizerCallback

    scheduler:
      callback: SchedulerCallback

  stage1:
    state_params:
      num_epochs: 120

    optimizer_params:
      optimizer: AdamW

    scheduler_params:
      scheduler: OneCycleLRWithWarmup
      init_lr: 0.0005
      num_steps: 115
      warmup_steps: 5
      lr_range: [0.001, 0.000005]







